version: '3'

volumes:
  storage:
  postgres:
  metabase:


services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 8079:5432
    restart: always

  app:
    build: .
    container_name: app
    command: python manage.py runserver 8080
    volumes:
      - ./:/usr/src/app
      - storage:/medias
    network_mode: host
    restart: always
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      - MB_DB_FILE:/metabase-data/metabase.db
    volumes:
      - metabase:/metabase-data/metabase.db
    ports:
      - 8081:3000
    restart: always
    depends_on:
      - postgres
