# Generated by Django 4.2.2 on 2023-06-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20, verbose_name='price'),
        ),
    ]
