# Generated by Django 4.2.2 on 2023-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_position_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionresult',
            name='pnl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='pnl'),
        ),
    ]
