# Generated by Django 4.2.2 on 2023-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_positionresult_pnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionresult',
            name='percent',
        ),
        migrations.AddField(
            model_name='position',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='positionresult',
            name='price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='price percent'),
        ),
    ]
