# Generated by Django 4.2.2 on 2023-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_remove_positionresult_percent_position_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='price',
            new_name='opening_price',
        ),
        migrations.RenameField(
            model_name='positionresult',
            old_name='price',
            new_name='closing_price',
        ),
        migrations.RemoveField(
            model_name='positionresult',
            name='price_percent',
        ),
        migrations.AddField(
            model_name='positionresult',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='position',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='balance'),
        ),
    ]
