# Generated by Django 4.2.2 on 2023-06-30 07:10

from django.db import migrations
import helpers.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_positionimage_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=helpers.db.fields.UpperCharField(unique=True),
        ),
    ]
