# Generated by Django 4.2.2 on 2023-06-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_symbol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionresult',
            name='pnl',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='pnl'),
        ),
    ]
