# Generated by Django 4.2.2 on 2023-06-30 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_alter_positionresult_pnl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('creation_date',), 'verbose_name': 'trade', 'verbose_name_plural': 'trades'},
        ),
        migrations.AlterModelOptions(
            name='positiontype',
            options={'ordering': ('name',), 'verbose_name': 'position type', 'verbose_name_plural': 'position types'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('slug',), 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ('name',), 'verbose_name': 'symbol', 'verbose_name_plural': 'symbols'},
        ),
        migrations.AddField(
            model_name='positionresult',
            name='closing_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
