# Generated by Django 4.2.2 on 2023-06-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_alter_position_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-opening_data',), 'verbose_name': 'trade', 'verbose_name_plural': 'trades'},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='creation_date',
            new_name='opening_data',
        ),
    ]
