# Generated by Django 4.2.2 on 2023-06-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionresult',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trades.position', verbose_name='trade'),
        ),
    ]
