# Generated by Django 4.2.2 on 2023-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_alter_positionresult_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionresult',
            name='percent',
        ),
        migrations.AddField(
            model_name='positionresult',
            name='balance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='balance percent'),
        ),
        migrations.AddField(
            model_name='positionresult',
            name='price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='price percent'),
        ),
    ]
