# Generated by Django 4.2.2 on 2023-06-30 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', helpers.db.fields.LowerCharField(unique=True)),
            ],
            options={
                'verbose_name': 'account type',
                'verbose_name_plural': 'account types',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', helpers.db.fields.LowerCharField(unique=True)),
            ],
            options={
                'verbose_name': 'transaction type',
                'verbose_name_plural': 'transaction types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=12, default=0, max_digits=20, verbose_name='price')),
                ('creation_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='creation date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.transactiontype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
